# Algebra lineal

## Matrices

In [2]:
import numpy as np
row = [1,2,3]
row

[1, 2, 3]

In [9]:
col = [[1],[2],[3]]
col

[[1], [2], [3]]

In [10]:
M = [[1,2,3],[4,5,6],[7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
M = [1][1]

IndexError: list index out of range

In [12]:
M = [0][0]

In [13]:
M

0

In [14]:
2*M

0

In [4]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.shape(M)

(3, 3)

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])

In [11]:
A+B

array([[2, 4],
       [6, 8]])

In [12]:
A.dot(B)

array([[ 7, 10],
       [15, 22]])

In [13]:
print(A.dot(B))

[[ 7 10]
 [15 22]]


In [14]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [15]:
print(A.transpose())

[[1 3]
 [2 4]]


In [16]:
print(A.trace())

5


In [17]:
np.linalg.matrix_rank(A)

2

In [18]:
np.linalg.matrix_power(A,5)

array([[1069, 1558],
       [2337, 3406]])

In [19]:
np.linalg.det(A)

-2.0000000000000004

In [20]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [27]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [30]:
np.linalg.det(x)

0.0

In [29]:
np.linalg.inv(x)

LinAlgError: Singular matrix

In [31]:
M[0]

array([1, 2, 3])

In [33]:
for row in M:
    print(row[0])

1
4
7
