# Copias y Vistas de arrays

In [2]:
import numpy as np

x =np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
y = x

In [5]:
y.shape =(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
z is x

False

In [9]:
y is x

True

In [10]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
t =x.view()

In [12]:
t.shape = (5,2)

In [13]:
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
s = x[0:2,1:3]
s

array([[1, 2],
       [6, 7]])

In [16]:
s[:] = 5
s

array([[5, 5],
       [5, 5]])

In [17]:
x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])