# NumPy

In [2]:
import numpy as np

In [3]:
L1 = [1,2,3,4,5,6,7,8] # Crear una lista

In [4]:
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x2 = np.array(L1, dtype='float32')

In [6]:
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

- bool_

- int_, intc, intp, int8, int16, int32, int64

- uint8, uint16, uint32, uint64

- float_, float16, float32, float64 (+/-9999999999e99999)

- complex_, complex64, complex128 (a+bi, a,b $\in$ float_)



In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,12,dtype=np.float64)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [12]:
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [14]:
np.linspace(1.,7.,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
x = np.zeros((8,3))

In [17]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
x.reshape((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
x =np.arange(24)

In [20]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
x.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
x.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [24]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [29]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
np.resize(x,(5,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios

1. Crear un array de datos con valores entre 5 y120

In [33]:
np.arange(5,121)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

2. Crear una matriz 4*4 con los valores desde 0 hasta 15

In [36]:
x = np.arange(0,16)
np.resize(x,(4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

3. Crear la identidad 7x7


In [39]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

4. Crear un array de 20 elementos y transformarlos en una matriz de 5x4

In [40]:
x = np.arange(20)
np.resize(x,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

5. Crear un array con 20 numeros con los valores entre 0 y 5 espaciados de forma uniforme

In [41]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])