## Funciones universales (ufunc)

- Unarias (elemento a elemento): sqrt, sin, cos, **2

- Binarias (Recibes dos arrays y devuelven uno normalmente): maximum, minimum

In [2]:
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x+3 # Unaria

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
x-3 # Unaria

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [6]:
x*3 # Unaria

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
x/3 # Unaria

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [9]:
alpha =  np.linspace(0,2*np.pi,4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [10]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [11]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [12]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [13]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [14]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [15]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [16]:
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [18]:
np.log(x)

<ipython-input-18-de666c833898>:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [19]:
np.sum(x)

45

In [20]:
np.nansum(x)

45

In [21]:
np.prod(x)

0

In [23]:
np.mean(x)

4.5

In [24]:
np.median(x)

4.5

In [25]:
np.min(x)

0

In [26]:
np.max(x)

9

In [27]:
np.std(x)

2.8722813232690143

In [28]:
np.var(x)

8.25

In [29]:
np.argmin(x)

0

In [30]:
np.argmax(x)

9

In [32]:
np.percentile(x, q=0.95)

0.08549999999999999

In [33]:
np.any(x) # Si alguno es verdadero es True

True

In [34]:
np.all(x) # si todos son verdaderos es True

False

In [46]:
np.random.seed(2021)
z = np.random.random((3,5)) # Generar datos aleatorios

In [47]:
z

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013],
       [0.0968944 , 0.05857129, 0.96239599, 0.61655744, 0.08662996]])

In [48]:
z.sum() # Suma de todos los valores dentro de la variable

7.115811794886615

In [49]:
z.sum(axis=0) # Suma de columnas

array([0.83103505, 0.97093375, 1.85426858, 1.59139104, 1.86818337])

In [50]:
z.sum(axis=1)

array([2.78821116, 2.50655156, 1.82104908])